#!/bin/bash

# pooters
# nodog
# 2015-03-12

# dotfilesymlinks
# creates symlinks from the home directory to any desired dotfiles in ~/adm/dotfiles

########## Variables

dir=~/adm/dotfiles                    # dotfiles directory
olddir=~/ATTIC/offal/dotfiles_old             # old dotfiles backup directory
files="bashrc mypromptcolors vim slate tmux.conf"    # list of files/folders to symlink in homedir

##########

# create olddir
echo -n "Creating $olddir for backup of any existing dotfiles..."
mkdir -p $olddir
echo "done"

# change to the dotfiles directory
echo -n "Changing to the $dir directory ..."
cd $dir
echo "done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $files; do
    echo "Moving existing $file from ~ to $olddir"
    mv ~/.$file ${olddir?}
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done

# because of my particular setup I link .profile to .bashrc
file=profile
sourcefile=bashrc
echo "Moving existing ${file?} from ~ to ${olddir?}"
mv ~/.profile ${olddir?}
echo "Creating symlink to ${file?} from ${sourcefile?}"
ln -s ${dir?}/${sourcefile} ~/.${file?}
